---
openapi: 3.0.3
info:
  title: Missão Startup Base API V1
  version: v1
paths:
  "/api/goals/done/index":
    post:
      summary: A goal as done
      tags:
      - Goals
      parameters: []
      responses:
        '200':
          description: goal marked as done
        '404':
          description: goal not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                goal_id:
                  type: integer
              required:
              - goal_id
  "/api/goals/done/show":
    post:
      summary: A goal as done
      tags:
      - Goals
      parameters: []
      responses:
        '200':
          description: goal marked as done
        '404':
          description: goal not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                goal_id:
                  type: integer
              required:
              - goal_id
  "/api/goals/done/many":
    post:
      summary: A goals as done
      tags:
      - Goals
      parameters: []
      responses:
        '200':
          description: goals marked as done
        '404':
          description: goals not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                goal_ids:
                  type: array
                  items:
                    type: integer
              required:
              - goal_ids
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
